version: "3.9"
   
services:
  db:
    image: postgres:11
    environment:
      - POSTGRES_DB=postgres # Change to env variable
      - POSTGRES_USER=postgres # Change to env variable
      - POSTGRES_PASSWORD=secret # Change to env variable
  web:
    build: .
    command: python app.py
    ports:
      - "5000:5000"
    depends_on:
      - db
